# Generated by Django 6.0.6 on 2026-06-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='酒店名称')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('business_hours', models.CharField(default='全天', max_length=50, verbose_name='营业时间')),
                ('logo', models.ImageField(blank=True, upload_to='hotel/', verbose_name='门店LOGO')),
                ('check_in_time', models.TimeField(default='14:00', verbose_name='默认入住时间')),
                ('check_out_time', models.TimeField(default='12:00', verbose_name='默认退房时间')),
                ('overtime_hourly_rate', models.DecimalField(decimal_places=2, default=50, max_digits=8, verbose_name='超时每小时加收')),
                ('holiday_surcharge_rate', models.DecimalField(decimal_places=2, default=0.3, max_digits=3, verbose_name='节假日溢价比例')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=200, max_digits=8, verbose_name='默认押金')),
            ],
            options={
                'verbose_name': '酒店信息',
                'verbose_name_plural': '酒店信息',
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='房型名称')),
                ('capacity', models.IntegerField(default=2, verbose_name='容纳人数')),
                ('bed_type', models.CharField(max_length=50, verbose_name='床型')),
                ('area', models.CharField(blank=True, max_length=20, verbose_name='面积')),
                ('facilities', models.TextField(blank=True, verbose_name='配套设施')),
                ('has_breakfast', models.BooleanField(default=False, verbose_name='含早餐')),
                ('description', models.TextField(blank=True, verbose_name='介绍')),
                ('image', models.ImageField(blank=True, upload_to='room_types/', verbose_name='展示图')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='日常价')),
                ('member_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='会员价')),
                ('weekend_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='周末价')),
                ('holiday_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='节假日价')),
                ('long_stay_discount', models.DecimalField(decimal_places=2, default=0.9, max_digits=3, verbose_name='长住折扣')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '房型',
                'verbose_name_plural': '房型',
                'db_table': 'room_type',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='房号')),
                ('floor', models.CharField(max_length=10, verbose_name='楼层')),
                ('status', models.CharField(choices=[('available', '空房'), ('booked', '已预订'), ('occupied', '入住中'), ('dirty', '脏房'), ('maintenance', '维修中'), ('reserved', '预留'), ('paused', '停用')], default='available', max_length=20, verbose_name='房间状态')),
                ('is_bookable', models.BooleanField(default=True, verbose_name='可预订')),
                ('facilities_status', models.TextField(default='正常', verbose_name='设施状态')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype', verbose_name='房型')),
            ],
            options={
                'verbose_name': '客房',
                'verbose_name_plural': '客房',
                'db_table': 'room',
            },
        ),
    ]
