# Generated by Django 6.0.6 on 2026-06-26 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待清洁'), ('cleaning', '清洁中'), ('cleaned', '已清洁'), ('reviewing', '待复检'), ('completed', '已完成'), ('issue', '问题上报')], default='pending', max_length=15, verbose_name='任务状态')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='退房时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('inspection_photo', models.ImageField(blank=True, upload_to='inspection/', verbose_name='巡检照片')),
                ('issue_description', models.TextField(blank=True, verbose_name='问题描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cleaner', models.ForeignKey(limit_choices_to={'role': 'housekeeping'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='保洁员')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '清洁任务',
                'verbose_name_plural': '清洁任务',
                'db_table': 'cleaning_task',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='入住时间')),
                ('check_out', models.DateTimeField(verbose_name='退房时间')),
                ('actual_check_in', models.DateTimeField(blank=True, null=True, verbose_name='实际入住')),
                ('actual_check_out', models.DateTimeField(blank=True, null=True, verbose_name='实际退房')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('booked', '已预订'), ('waiting', '待入住'), ('in_stay', '在店中'), ('extended', '已续住'), ('settling', '待结算'), ('completed', '已完成'), ('cancelled', '已取消'), ('refunded', '已退款'), ('abnormal', '异常')], default='pending', max_length=15, verbose_name='订单状态')),
                ('room_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='房费')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额')),
                ('points_used', models.IntegerField(default=0, verbose_name='使用积分')),
                ('total_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='额外消费')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实付金额')),
                ('guest_count', models.IntegerField(default=1, verbose_name='入住人数')),
                ('guest_names', models.TextField(blank=True, verbose_name='同住人')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作员工')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('dining', '餐饮'), ('goods', '日用品'), ('laundry', '洗衣'), ('entertainment', '棋牌'), ('other', '其他')], max_length=20, verbose_name='消费类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='消费时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '消费账单',
                'verbose_name_plural': '消费账单',
                'db_table': 'consumption_bill',
            },
        ),
    ]
